### ISSUE TITLE
Download count not incrementing

### ISSUE THREAD

**Issue by jon--lee** [aclark4life/vanity#18] opened 2015-08-19 03:39 UTC
Hi,
I noticed a few days ago that download counts weren't incrementing anymore. I ran
```
$ vanity django
```
twice with about a day in between and got the same download count (`17,560,592`). It seemed suspicious that no one would download Django in that time period. I tried using PyPIXmlRpc on its own and also found that the download count was the same and hadn't incremented. Maybe this is an issue at PyPI?

Thanks

**Comment by aclark4life** [comment] 2015-08-19 10:52
Confirmed, maybe @dstufft knows something. Thanks for reporting

**Comment by pooya-eghbali** [comment] 2015-08-20 08:36
PyPI had a database migration on Aug 15, 2015 and pypi.python.org was down. I noticed this issue (download count not increment) from the day after the database migration. It is probably an issue at PyPI.

**Comment by dstufft** [comment] 2015-08-20 10:19
Should be fixed now I think.

**Comment by aclark4life** [comment] 2015-08-20 11:47
Yep, thanks
```
$ vanity -q django
Django has been downloaded 17,562,306 times!
```

**Closed by aclark4life** 2015-08-20 11:47 UTC

**Comment by jon--lee** [comment] 2015-08-28 01:49
I think it's frozen again.
```
$ vanity -q django
Django has been downloaded 17,626,069 times!
```
It's been saying that for three days now.
@dstufft how was it fixed previously?

**Comment by madmat3001** [comment] 2016-02-18 11:10
It's frozen for me again, since about the beginning of february...

**Comment by aclark4life** [comment] 2016-02-18 14:58
@madmat3001 Yep, this is almost certainly a PyPI issue. Probably best to open a ticket here: https://bitbucket.org/pypa/pypi/issues CC: @dstufft
